# Generated by Django 5.0.2 on 2024-02-19 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('fullName', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=6)),
                ('mobile', models.CharField(max_length=15)),
                ('defaultAddress', models.BooleanField(default=False)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('shipment_created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
