# Generated by Django 5.0.2 on 2024-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='https://wallpapers.com/images/hd/animated-young-girl-nezuko-7gjo3tyerpb2dyy1.webp', max_length=100),
        ),
    ]
