# Generated by Django 5.0.2 on 2024-02-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'customer'), (1, 'admin')], null=True),
        ),
    ]
