# Generated by Django 5.0.2 on 2024-02-19 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('discountedPrice', models.DecimalField(decimal_places=2, max_digits=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('totalItems', models.IntegerField()),
                ('paymentMethod', models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=10)),
                ('paymentStatus', models.CharField(default='pending', max_length=100)),
                ('deliveryStatus', models.CharField(default='PENDING', max_length=100)),
                ('orderStatus', models.CharField(max_length=100)),
                ('totalPrice', models.IntegerField()),
                ('discountedPrice', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
