# Generated by Django 5.0.2 on 2024-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='title',
            field=models.CharField(default='Sahasam', max_length=100),
            preserve_default=False,
        ),
    ]
