# Generated by Django 5.0.2 on 2024-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'sucess'), ('failed', 'failed')], default='pending', max_length=100),
        ),
    ]
