# Generated by Django 5.0.2 on 2024-02-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_order_deliverystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=100),
        ),
    ]
