# Generated by Django 5.0.2 on 2024-02-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryDate',
            field=models.DateTimeField(null=True),
        ),
    ]
