# Generated by Django 5.0.2 on 2024-02-19 12:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('discountPercentage', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=99999, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('stock', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('sizes', models.CharField(max_length=100, null=True)),
                ('colors', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='Products.product')),
            ],
        ),
    ]
