# Generated by Django 5.0.2 on 2024-02-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/products'),
        ),
    ]
