# Generated by Django 5.0.2 on 2024-03-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
