# Generated by Django 5.0.2 on 2024-03-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_alter_order_orderstatus'),
        ('Products', '0005_remove_product_colors_remove_product_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
