# Generated by Django 5.0.2 on 2024-03-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_colors_product_orders_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='orders',
        ),
    ]
