# Generated by Django 5.0.2 on 2024-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_remove_product_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
